repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      # - id: no-commit-to-branch  # TODO: reinstate
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
