# Re-usable steps for a GitHub Action that needs `uv`.
# As a side-effect also installs `just` - might want to extract this to a separate action.
#
# Usage:
#   ```
#   steps:
#     - uses: ./.github/actions/uv
#     - run: uv ...
#       shell: bash
#   ```
#
# (c) 2024 Alberto Morón Hernández

name: 'Install uv'
description: 'Check out project code, set up Python, install uv'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
    # TODO: can switch to apt-get when upgrade Actions runner to ubuntu-24.04
    - run: |
        sudo snap install --edge --classic just
        curl -LsSf https://astral.sh/uv/install.sh | sh
        just venv
      shell: bash
