# Re-usable GitHub Action that runs the end-to-end suite.
#
# Usage:
#   ```
#   steps:
#     - uses: ./.github/actions/e2e
#   ```
#
# (c) 2024 Alberto Morón Hernández

name: 'e2e'
description: 'Run end-to-end Playwright tests'

runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/uv
    # must run as its own step because environment variables are
    # only available in steps following the one that sets them.
    - run: ./local/read_dotenv.sh .env.test
      shell: bash
      # dotenv intentionally left blank when calling 'just'
    - run: |
        just dotenv= install-deps-test
        just dotenv= e2e
      shell: bash
