# DepositDuck Continuous Integration pipeline
#
# (c) 2024 Alberto Morón Hernández
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    env:
      SKIP: ${{ github.ref == 'refs/heads/master' && 'no-commit-to-branch' || '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1

  test:
    needs:
      - pre_commit
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/uv
        - run: |
            make install-deps-test
            make test
