# DepositDuck Continuous Integration pipeline
# Runs when a Pull Request is merged into the 'main' branch.
#
# (c) 2024 Alberto Morón Hernández
name: CI

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pre-commit

  test:
    needs:
      - pre_commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test

  containerise:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          # assign the base branch name to GIT_REF & lowercase repository name to REPO_NAME
          echo "GIT_REF=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"
        shell: bash
      - uses: ./.github/actions/containerise
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/${{ env.GIT_REF }}:latest
